// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteComment struct {
	ID      string `json:"_id"`
	Message string `json:"message"`
}

type DeletePhoto struct {
	ID string `json:"id"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewComment struct {
	Message string `json:"message"`
}

type NewPhoto struct {
	Title    string `json:"title"`
	Caption  string `json:"caption"`
	PhotoURL string `json:"photo_url"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Age      int    `json:"age"`
}

type UpdateComment struct {
	ID      string `json:"_id"`
	Message string `json:"message"`
}

type UpdatePhoto struct {
	ID       *string `json:"id"`
	Title    string  `json:"title"`
	Caption  string  `json:"caption"`
	PhotoURL string  `json:"photo_url"`
}

type UpdateUser struct {
	ID       *string `json:"_id"`
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
	Age      *int    `json:"age"`
}
